Dev
rpiml/okcollege-survey-training-preprocessor pull request #2
Opened 2016-11-16 06:45 UTC by zlalvani

Preprocesses survey training data

2016-11-17 00:18 UTC, seveibar requested changes

2016-11-17 00:18 UTC, seveibar commented on .travis.yml
> +  - wget https://raw.githubusercontent.com/rpiml/okcollege-dev/master/assets/form.json -P ./assets
you should pull the entire assets directory :penguin:

2016-11-17 00:18 UTC, seveibar commented on docker-test.yml
> +    command: "/bin/bash -c \"cd /usr/src/app && pip install -r requirements.txt && python -u test.py\""
what is python -u?

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +
extra spaces :penguin:

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +def query_db(query, database='postgres', host='localhost', user='postgres', password='', response=True, autocommit=False):
query_db should be pulled from environment variables

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +        if response:
needs comments

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +    response_table = io.StringIO()
needs comments,  doc string

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +            seen = set()
what is this

2016-11-17 00:18 UTC, seveibar commented on helpers.py
> +            seen = set()
"seen"

2016-11-17 00:36 UTC, zlalvani commented on docker-test.yml
> +    command: "/bin/bash -c \"cd /usr/src/app && pip install -r requirements.txt && python -u test.py\""
flag for unbuffered output

2016-11-17 00:49 UTC, seveibar requested changes

2016-11-17 00:49 UTC, seveibar commented on test.py
> +        result = helpers.query_db('SELECT uuid, content FROM survey_response', database='postgres')
redundant database specification, i think a singleton is appropriate here

2016-11-17 00:49 UTC, seveibar commented on test.py
> +if __name__ == '__main__':
needs comments, would also recommend testing framework

2016-11-17 00:49 UTC, seveibar commented on test.py
> +            print('%s <-> %s' % (line.strip(), output_features_list[i].strip()))
this should all be broken up into functions and commented

2016-11-17 00:49 UTC, seveibar commented on preprocessor.py
> +    channel.queue_bind('survey-training-preprocessor', exchange='preprocessor', routing_key='survey-training-preprocessor')
I don't understand these, are they obvious? Why an exchange preprocesser? Why declare the exchange preprocessor/direct?

2016-11-17 00:49 UTC, seveibar commented on preprocessor.py
> +            time.sleep(1)
sleep for less time

2016-11-20 23:09 UTC, seveibar approved these changes
nice revision!

2016-11-20 23:09 UTC, seveibar commented on helpers.py
> +        psql_conn.close()
possible change to singleton? Seems to weird to open and close connections every time :penguin:  should as an issue after merge

2016-11-20 23:09 UTC, seveibar commented on helpers.py
> +        - the result of a database query (as a list of JSON objects)
label with appropriate parameter

2016-11-20 23:09 UTC, seveibar commented on helpers.py
> +        - the result of a database query (as a list of JSON objects)
i.e. `result: the result of a database query (as a list of JSON objects)`

2016-11-20 23:09 UTC, seveibar commented on helpers.py
> +        - the result of a database query (as a list of JSON objects)
:penguin:

2016-11-20 23:09 UTC, merged